development:
  adapter: postgresql
  # username: pguser
  # password: pguser
  database: bingo_development
  host: localhost

test:
  adapter: postgresql
  # username: pguser
  # password: pguser
  database: bingo_test
  host: localhost

staging:
  adapter: postgresql
  database: bingo_staging
  host: localhost

production:
  adapter: postgresql
  database: bingo_development
  host: localhost